language: cpp
sudo: required
dist: trusty
services:
- docker
git:
  depth: 5
notifications:
  slack:
    secure: iS767Cc5C6lnDADvTqt5aypq4XaVWvgqJsdWTV1ia6E8tGxzbf/jRtRkKQkzEFrnN7xjc/q93/Gd1kcJFwyq0vA0eeX8GhnlJx1mPxktgeguNiKzCaiBmyLiixpwy/yClHdvrmv/mnR4PbkaG4tYBod6n4BpnaQQNqL3V0ie25rF4PJtpos+QQmQzCxzEU8nXm9f54pYVfVX5v9rkz0vmltX7GceYayvcMHipBCaoYDJNQqVAGr0jt+wfw93BFHsOb+EQBCB4Gw5MRNfiDeYRjrI6SXkPeb6S0R7c7fOGnk68hDI1j9Yp1i+VRpxbKRGwEeWHXhI6A7XeUenSdDvIZp/42nubdmQcXjeCLk6NRGflWPpwk5Evy74csN12hjE+cGfQpI9/oKnufly15+8BQL+PUGtaFa8rU2UfevdK32IpMeOeY5XbH6KQ4OXLAzW5211tZZaL0BTZp2TEdTskgtSDuyq3oNDAkWxH9BQYtWbAVqRgPu1nl5oXj9IG+q2UI1QG0JuKQ9hduFlyQ8NSCXVcQOQwpzW3CDAMSUl2Pe00/djgi6sdHu3i3ur9HEnrniwskl+VElUXPJYmA82U1UVF6NFhySS64y3QRdHNXNs7iQBTywbjSRSVW6YQB4bW8JY2ykyaJEjpXtXSumEYFjLvRFhU0cZDU4lqiO7ZlA=
  irc:
  - ircs://chat.freenode.net:7070#grangerhub
  email:
    on_success: change
    on_failure: change
matrix:
  include:
  - os: linux
    env: PLATFORM=linux
    before_install:
    - docker pull grangerhub/tremulous13:latest
    - docker run -e PLATFORM -v $(pwd):/usr/src grangerhub/tremulous13:latest ./misc/travis-ci-docker-build.sh
    script:
    - true
  - os: linux
    env: PLATFORM=mingw32
    before_install:
    - docker pull grangerhub/tremulous13:latest
    - docker run -e PLATFORM -v $(pwd):/usr/src grangerhub/tremulous13:latest ./misc/travis-ci-docker-build.sh
    script:
    - true
  - os: linux
    env: PLATFORM=mingw32 ARCH=x86
    before_install:
    - docker pull grangerhub/tremulous13:latest
    - docker run -e ARCH -e PLATFORM -v $(pwd):/usr/src grangerhub/tremulous13:latest
      ./misc/travis-ci-docker-build.sh
    script:
    - true
  - os: osx
    osx_image: xcode8
    compiler: clang
    env: ARCH=x86_64
    before_install:
    - rm -rf build
    script:
    - "./misc/travis-ci-build.sh"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: g9HIz82c3vz3bl7vsMuODCz6kwf4IogJGw8V1Pn7TapXTeO9JnR1BqAhQbuqjPEBsgnIf+zwNblzBYmSyihB5I8JC8GiyhX/5tq5C/fd0z+uAH3Gsm5BFowRRUjVQlneH61NY4LP8H6h1KfkFBlD3NfW1D8kCa7vUyEh4Lj11wJMj9WgYctYfPu0rW2f8mCBSJ5VPR0EDNnJ8DV0EKEKmv7tiF6sY6eLuMg7VMtSPCCd/NkSQz1A04xYi6AwghrCJ8EZvkBhRIqgUGFL8y2si2Dt30fEG4nz4eDuqm17JoI9NX6Iz7v8iwU2CBL4wrDlqVYcncYxFqL89ZcXAmVHBl9eqqPKfA0KzR10IbkjVuVGvM0eQTOlGayDNalutZ0UtDuqPnMjHALpH+AsGUCwdYCQN5KL6b/xsgmQYUHuRE2ThbVk6MC7UbVSj6BQPiff9q41lSlHin2tkL9XUrGea0RY9d8F5dgT1oiYygUOpXcXA8slme2zvkuaNDrgFgkqU9ii3zqhqJxcFHkDIOmqxJJhyKcI4v6BWCz0evZzV4Qv3LpQyZeKJhmCAH5yU3xJYwV5ePoHrEeZc4a9y46V6R2hMttwawyR1TPZeT4PvEAFtusmfpmVeVlLhB9mmINK/D9LmuTEo0CdBioCgsIM1YQLFT8727yC/acB61dYowE=
  file_glob: true
  file: build/*.zip
  on:
    repo: dGr8LookinSparky/tremulous
    tags: true
